### PR TITLE
Add SubscriptionDetails to Transaction struct

### PR DESCRIPTION
**Pull request by ducnt114**

### CODE REVIEW

**Comment by ducnt114** [comment]
I have replaced `BillingPeriod` with existing `Subscription` struct and updated test case for new field.

**Comment by leighmcculloch** [comment]
Three tests are failing, but two of them are also failing on master so we can ignore those. The one that failed had this error message:
>--- FAIL: TestAllTransactionFields (4.03s)
>	transaction_integration_test.go:888: expected tx2.RiskData.ID not to be empty

I'm re-running the build to see if it was temporal.

**Comment by leighmcculloch** [comment]
The rerun of the tests showed that test pass, so looks good!

**Comment by leighmcculloch** [comment]
@ducnt114 I just took a look at the other Braintree SDKs and I realized that other SDKs actually organize this structure the same way you had originally, but with a different name. e.g. The ruby SDK has a `SubscriptionDetails` with the two billing period fields. Looking at the developer docs those are the only two fields that get returned. Sorry for the misdirection asking you to make it like the Java SDK.

I've changed it back to how you had it with the new struct instead, and renamed it to `SubscriptionDetails`.

I also added a test for when the transaction is not part of a subscription and added custom unmarshalling logic so that the `SubscriptionDetails` is `nil` on the `Transaction` when there is no subscription.

**Pull request merged**
