### PR TITLE
adds account updater daily report to possible webhook subjects

### PR DESCRIPTION
**Pull request by Seklfreak**
This pull request will make the fields sent by the `AccountUpdaterDailyReportWebhook` Webhook available to the `WebhookNotification` struct.

### CODE REVIEW

**Comment by Seklfreak** [comment]
Thanks for taking a look, I will add it soon!

**Comment by leighmcculloch** [comment]
Thanks @Seklfreak, looks great. I'll merge it when the builds pass.

**Comment by leighmcculloch** [comment]
Could you add a function to access the subject? Looks like the build is failing on needing that function. Good thing your test followed the same pattern as the existing ones 😃.

e.g. https://github.com/lionelbarrow/braintree-go/blob/0d5adc50df2d560725c7d215e8838e0fa8c0b540/webhook_notification.go#L57-L63

**Comment by Seklfreak** [comment]
Yep, just realised that I forgot to add it. Hopefully it will work now. Thanks. 🙏

**Comment by Seklfreak** [comment]
Sorry, I think I'm trying to do too many things at once. I think this should work.

**Comment by Seklfreak** [comment]
Everything is working now. Just fixed the error message in the last commit. Sorry for so many commits, should have checked it better!

**Comment by leighmcculloch** [comment]
Thanks @Seklfreak! And don't worry about the many commits. That's the whole point of opening PRs: to iterate and get it into shape! Thanks for iterating on it so promptly.

**Comment by Seklfreak** [comment]
Thanks for the quick merge 😊

**Pull request merged**
