### PR TITLE
Tj refund ids

### PR DESCRIPTION
**Pull request by codewitch**
Adding refund ids to the transaction return object.

### CODE REVIEW

**Comment by lionelbarrow** [comment]
You've got a typo on the struct tag in refunded transaction ID - `refundied`. I think you should add some tests before I merge this. It should be really easy to extend the test `TestTransactionCreateSettleAndFullRefund` with assertions that cover these fields.

**Comment by lionelbarrow** [comment]
Sorry, didn't mean to hit the close button :) Just say something in the thread when you've added some tests.

**Comment by codewitch** [comment]
Thanks for the suggestion! I fixed the typo and made checks in the tests. Let me know if you have any other comments :)

**Comment by lionelbarrow** [comment]
Awesome, thanks!

**Pull request merged**
