### PR TITLE
Added transaction to BraintreeError

### PR DESCRIPTION
**Pull request by knifeedge**

### CODE REVIEW

**Comment by lionelbarrow** [comment]
Hey this looks pretty good, can you add a test around settlement?

**Comment by knifeedge** [comment]
Thanks, I've added a basic test for settlement, I'll add more to it if needed.

**Comment by knifeedge** [comment]
Sorry I didn't get this test to pass till now. I fixed the test since I didn't realize that there are 4 concurrent tests updating the account at the same time, so it's a really simple test to check card types. Let me know if you think of a better way to test the summary.

**Comment by lionelbarrow** [comment]
Looks great, thanks very much!

**Pull request merged**
