### PR TITLE
Add payment-method-nonce to Customer

### PR DESCRIPTION
**Pull request by lquach**
To create a payment method along with a customer.
The Ruby documentation: https://developers.braintreepayments.com/reference/request/customer/create/ruby#customer-with-a-payment-method

### CODE REVIEW

**Comment by leighmcculloch** [comment]
@lquach: Thanks! Could you add a test to `customer_integration_test.go` that creates a customer using one of the fake nonces?

**Comment by lquach** [comment]
Test added.

**Comment by leighmcculloch** [comment]
Nice! Thank you!

**Comment by lquach** [comment]
@leighmcculloch thank you!

**Comment by leighmcculloch** [comment]
Aside to this we should probably looking at splitting `Customer` into `Customer` (the data returned) and `CustomerRequest` (the data sent when creating/updating) like we recently did to `Transaction`, since it now has `PaymentMethodNonce` which is only used when creating the customer and not in the response.

**Pull request merged**
