### PR TITLE
Added another example, organized the code

### PR DESCRIPTION
**Pull request by tsirolnik**
So basically I've added an example of a subscription based payment and I've organized the examples directory.
Nothing big, but, it could save others a lot of time.

### CODE REVIEW

**Comment by lionelbarrow** [comment]
Thanks! This looks good. I'm going to tweak the way the credentials are loaded to use env variables and edit the comments and merge soon.

**Comment by tsirolnik** [comment]
Thanks! Appreciated.

**Comment by tsirolnik** [comment]
argh, how can I reopen it?

**Comment by tsirolnik** [comment]
Thanks a lot!

**Pull request merged**
