### PR TITLE
Add support for Addons and Discounts for Subscriptions.

### PR DESCRIPTION
**Pull request by TamalSaha**

### CODE REVIEW

**Comment by maxsz** [comment]
Due to the recent activity, we're very close to switching back from our custom fork to this 'official' one. One point that's missing is the addon support for subscriptions. I was just about to create a pull request, when I found this one. Looks very promising. @leighmcculloch what do you think?

**Comment by leighmcculloch** [comment]
@maxsz: Planning to look at it this week! 😃

**Comment by leighmcculloch** [comment]
Before we merge these additions I think we should increase the test coverage of subscriptions, and include tests for the add, update and remove modification types. We should probably stagger these changes since this PR is doing several things.

I'm thinking lets break it up into the following PRs:

* Add add expectations to tests for marshaling and unmarshaling all fields.
* Add `SubscriptionRequest` for `Create` and `Update`.
* Add descriptors.
* Add modifications (addons and discounts) to `SubscriptionRequest`.
* Add addons and discounts to `Subscription`.

**Comment by TamalSaha** [comment]
@leighmcculloch / @maxsz , you guys are welcome to push separate prs. I doubt that I will find time for that in the near future.

**Comment by leighmcculloch** [comment]
All the code in this PR isn't merged yet. Github marked it as merged because it's in the history in #107, but I'd stripped back the changes. Will continue to open more PRs with the remaining changes; stay tuned.

**Pull request merged**
